In [ ]:
# numpy
# dict details 


## student details 

In [1]:
dct={12345 : {"st_name" :"ang",
              "nd_name" :"ros",
              "mail" : "aweq@fsk",
              "batch" : "cse",
              "year": 3},
     12346:{"st_name" :"emy",
              "nd_name ":"mar",
              "mail" : "abc@fsk",
              "batch" : "cse",
              "year": 3}}
              

In [2]:
dct


{12345: {'st_name': 'ang',
  'nd_name': 'ros',
  'mail': 'aweq@fsk',
  'batch': 'cse',
  'year': 3},
 12346: {'st_name': 'emy',
  'nd_name ': 'mar',
  'mail': 'abc@fsk',
  'batch': 'cse',
  'year': 3}}

In [3]:
dct[12345]

{'st_name': 'ang',
 'nd_name': 'ros',
 'mail': 'aweq@fsk',
 'batch': 'cse',
 'year': 3}

In [4]:
dct[12345]["st_name"]

'ang'

In [7]:
print("--"*25)
for i in dct.keys():
    print(i)

--------------------------------------------------
12345
12346


In [12]:
n=int(input("Enter the register number: "))
print("--- - "*5)
for i in dct.keys():
    if i==n:
        print("First name  :",dct[i]["st_name"])
        print("Second name :",dct[i]["nd_name"])
        print("Gmail       :",dct[i]["mail"])
        print("Year        :",dct[i]["year"])
        print("Batch name  :",dct[i]["batch"])
print("--- - "*5)
        

Enter the register number: 12345
--- - --- - --- - --- - --- - 
First name  : ang
Second name : ros
Gmail       : aweq@fsk
Year        : 3
Batch name  : cse
--- - --- - --- - --- - --- - 


## To add  details 

In [14]:
reg_no =int(input("Register no :"))
fn=str(input("first name :"))
sn=str(input("second name :"))
gm=str(input("gamil :"))
y=int(input("year :"))
bat=str(input("batches :"))

temp={}

temp["st_name"]=fn
temp["nd_name"]=sn
temp["mail"]=gm
temp["year"]=y
temp["batch"]=bat

dct[reg_no]=temp


Register no :12347
first name :rod
second name :msr
gamil :abf@gmail.com
year :2
batches :eee


In [15]:
dct

{12345: {'st_name': 'ang',
  'nd_name': 'ros',
  'mail': 'aweq@fsk',
  'batch': 'cse',
  'year': 3},
 12346: {'st_name': 'emy',
  'nd_name ': 'mar',
  'mail': 'abc@fsk',
  'batch': 'cse',
  'year': 3},
 12347: {'st_name': 'rod',
  'nd_name': 'msr',
  'mail': 'abf@gmail.com',
  'year': 2,
  'batch': 'eee'}}

## section details 

In [20]:
section={ "kl123" :{"hod" :234, "degree":"cse","teacher":[123,124]},
          "kl345" :{"hod" :324, "degree":"eee","teacher":[234,245]},
          "kl365" :{"hod" :456, "degree":"ece","teacher":[125,126]}
         } 

In [21]:
section

{'kl123': {'hod': 234, 'degree': 'cse', 'teacher': [123, 124]},
 'kl345': {'hod': 324, 'degree': 'eee', 'teacher': [234, 245]},
 'kl365': {'hod': 456, 'degree': 'ece', 'teacher': [125, 126]}}

# teacher details

In [22]:
teacher = { 234 : {'first_name':'Ashish', 
                 'mail' : 'abc@gmail.com'},
      324 :  {'first_name':'Abhishek', 
                 'mail' : 'abc@gmail.com'},
      456 :  {'first_name':'Abhi', 
                 'mail' : 'abc@gmail.com'},
      123 : {'first_name':'Abhimanyu', 
                 'mail' : 'abc@gmail.com'},
      124 : {'first_name':'Karan', 
                 'mail' : 'abc@gmail.com'},
      125 : {'first_name':'Arjun', 
                 'mail' : 'abc@gmail.com'},
      126 : {'first_name':'Ayush', 
                 'mail' : 'abc@gmail.com'},
      234 : {'first_name':'Abkush', 
                 'mail' : 'abc@gmail.com'},
      245 : {'first_name':'Bharat', 
                 'mail' : 'abc@gmail.com'}}

In [31]:
print("hod :",teacher[section["kl123"]["hod"]])

hod : {'first_name': 'Abkush', 'mail': 'abc@gmail.com'}


In [34]:
print(" teachers")
print("-- - "*5)
for i in section["kl123"]["teacher"]:
    print(teacher[i]["first_name"])

 teachers
-- - -- - -- - -- - -- - 
Abhimanyu
Karan


In [40]:
print(" teachers")
print("-- - "*5)
for i in section.keys():
    print(f"section {i}")
    print("...."*3)
    for j in section[i]["teacher"]:
         print(teacher[j]["first_name"])
    print("...."*4)

 teachers
-- - -- - -- - -- - -- - 
section kl123
............
Abhimanyu
Karan
................
section kl345
............
Abkush
Bharat
................
section kl365
............
Arjun
Ayush
................


# NUMPY

In [2]:
!pip  install numpy

In [3]:
import numpy

In [5]:
# floating point number ranging from 0 to 1
numpy.random.random()

0.6478657950230583

## 1.heads or tail probabilty

In [12]:
if(numpy.random.random()>.5):
    print("heads")
else:
    print("tail")

heads


In [14]:
## array using numpy
numpy.random.random((2,2))

array([[0.31114428, 0.04320989],
       [0.68734323, 0.22703512]])

In [15]:
numpy.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# acts a for loop
numpy.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
# divides the range into equall parts
numpy.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [21]:
# assiging numpy as other short words
import numpy as np

In [22]:
np.random.random()

0.8809924002808311

In [27]:
np.random.random((2,3))

array([[0.48498556, 0.06799524, 0.29234059],
       [0.90686219, 0.63735287, 0.04496372]])

In [25]:
arr=np.random.random((2,3))
arr

array([[0.61462842, 0.00914884, 0.04881349],
       [0.21983629, 0.01649366, 0.91527044]])

In [26]:
type(arr)

numpy.ndarray

## reshaping the array

In [28]:
## a numpy function()
arr.shape

(2, 3)

In [36]:
arr.size

6

In [34]:
# while reshaping it should have the same number of elemenṭs as the array
arr.reshape((3,2))

array([[0.61462842, 0.00914884],
       [0.04881349, 0.21983629],
       [0.01649366, 0.91527044]])

In [35]:
np.reshape(arr,(6,1))

array([[0.61462842],
       [0.00914884],
       [0.04881349],
       [0.21983629],
       [0.01649366],
       [0.91527044]])

## array flattern

In [42]:
arr=np.random.random((5,4))

In [43]:
arr

array([[0.87256441, 0.44433607, 0.204728  , 0.8547389 ],
       [0.96789991, 0.85260136, 0.232329  , 0.35599876],
       [0.88407326, 0.18188801, 0.45880108, 0.37288764],
       [0.82105015, 0.93024765, 0.01144708, 0.76357733],
       [0.80257113, 0.30680183, 0.79109675, 0.11493553]])

In [44]:
arr.size

20

In [51]:
arr=arr.flatten()

In [53]:
arr.size

20

In [56]:
# it flatten the aray shape to 0 rows
arr.shape

(20,)

## array to list and vise-versa

In [1]:
import numpy

In [6]:
lst=[1,2,3,4,5,6]

In [7]:
type(lst)

list

In [8]:
# using numpy to convert
arr=numpy.array(lst)

In [9]:
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
# from array to list 
msn=list(arr)

In [13]:
# list
msn

[1, 2, 3, 4, 5, 6]

In [16]:
## list cannot be added ,sub,or divided by each element but array can so use array
ltr=[1,2,3,5,6]
ar=numpy.array(ltr)
print(ar)

[1 2 3 5 6]


## arthimatic operations in arrays

In [17]:
## error if we try to add the things in  the list 
print(ltr+1)

TypeError: can only concatenate list (not "int") to list

In [18]:
print(ar+2)
print(ar-1)
print(ar*3)
print(ar/2)

[3 4 5 7 8]
[0 1 2 4 5]
[ 3  6  9 15 18]
[0.5 1.  1.5 2.5 3. ]


In [19]:
arr

array([1, 2, 3, 4, 5, 6])

In [20]:
arr+=5

In [21]:
arr

array([ 6,  7,  8,  9, 10, 11])

In [22]:
arr.max()

11

In [23]:
arr.min()

6

In [24]:
arr.mean()

8.5

## operations on array

In [3]:
arr2=numpy.array([[1,2,3,4,5],[3,4,5,6,7]])

In [4]:
arr2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [5]:
arr2.min()

1

In [1]:
## to get row wise highest rank is 
arr2.min(ais=0)

NameError: name 'arr2' is not defined